# Generated by Django 4.1.7 on 2023-03-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hummingbot_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
